In [74]:
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px 
import plotly.figure_factory as ff
import plotly.graph_objects as go 
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter('ignore')
import random
import datetime

In [80]:
data = yf.download(['BITF', 'AAPL', "TSLA"], start = "2020-01-01", auto_adjust=False)

[*********************100%***********************]  3 of 3 completed

In [81]:
data

Price        Adj Close                          Close                     \
Ticker            AAPL   BITF        TSLA        AAPL   BITF        TSLA
Date
2020-01-02   72.468254  0.382   28.684000   75.087502  0.382   28.684000
2020-01-03   71.763718  0.382   29.534000   74.357498  0.382   29.534000
2020-01-06   72.335556  0.404   30.102667   74.949997  0.404   30.102667
2020-01-07   71.995361  0.513   31.270666   74.597504  0.513   31.270666
2020-01-08   73.153488  0.479   32.809334   75.797501  0.479   32.809334
...                ...    ...         ...         ...    ...         ...
2026-01-12  260.250000  3.030  448.959991  260.250000  3.030  448.959991
2026-01-13  261.049988  3.110  447.200012  261.049988  3.110  447.200012
2026-01-14  259.959991  2.940  439.200012  259.959991  2.940  439.200012
2026-01-15  258.209991  2.840  438.570007  258.209991  2.840  438.570007
2026-01-16  255.529999  2.950  437.500000  255.529999  2.950  437.500000

Price             High                            Low                     \
Ticker            AAPL   BITF        TSLA        AAPL   BITF        TSLA
Date
2020-01-02   75.150002  0.382   28.713333   73.797501  0.382   28.114000
2020-01-03   75.144997  0.382   30.266666   74.125000  0.382   29.128000
2020-01-06   74.989998  0.404   30.104000   73.187500  0.404   29.333332
2020-01-07   75.224998  0.513   31.441999   74.370003  0.426   30.224001
2020-01-08   76.110001  0.479   33.232666   74.290001  0.479   31.215334
...                ...    ...         ...         ...    ...         ...
2026-01-12  261.299988  3.040  454.299988  256.799988  2.770  438.000000
2026-01-13  261.809998  3.240  451.809998  258.390015  3.040  443.950012
2026-01-14  261.820007  3.200  443.910004  256.709991  2.910  434.220001
2026-01-15  261.040009  2.980  445.359985  257.049988  2.810  437.649994
2026-01-16  258.899994  3.040  447.250000  254.929993  2.810  435.260010

Price             Open                        Volume
Ticker            AAPL   BITF        TSLA       AAPL      BITF       TSLA
Date
2020-01-02   74.059998  0.382   28.299999  135480400         0  142981500
2020-01-03   74.287498  0.382   29.366667  146322800         0  266677500
2020-01-06   73.447502  0.404   29.364668  118387200     25000  151995000
2020-01-07   74.959999  0.426   30.760000  108872000     57900  268231500
2020-01-08   74.290001  0.479   31.580000  132079200      1000  467164500
...                ...    ...         ...        ...       ...        ...
2026-01-12  259.160004  2.780  441.230011   45263800  48807600   61649600
2026-01-13  258.720001  3.115  450.200012   45730800  59565900   53719200
2026-01-14  259.489990  3.190  442.809998   40019400  65971100   57259500
2026-01-15  260.649994  2.970  441.130005   39388600  34091800   49465800
2026-01-16  257.899994  2.835  439.500000   72018600  42309400   60047300

[1519 rows x 18 columns]

# Function to prepare the data that returns adjusted closing price DataFrame

In [ ]:
def data_prep(data):

    data = data.reset_index()
    df = data[["Date", "Adj Close", "Close", "High", "Low", "Open"]]
    adj_close_price_df = df["Adj Close"]
    adj_close_price_df.insert(loc = 0, column = "Date", value = df["Date"])
    
    return adj_close_price_df

In [95]:
df = data_prep(data)
display(df.head())

Ticker       Date       AAPL   BITF       TSLA
0      2020-01-02  72.468254  0.382  28.684000
1      2020-01-03  71.763718  0.382  29.534000
2      2020-01-06  72.335556  0.404  30.102667
3      2020-01-07  71.995361  0.513  31.270666
4      2020-01-08  73.153488  0.479  32.809334

# Creating a function to return Percentage Daily Returns DataFrame

In [99]:
def percentage_daily_returns(adj_close_df):
    daily_returns_df = adj_close_df.copy()
    for column in daily_returns_df.columns[1:]:
        daily_returns_df[column] = adj_close_df[column].pct_change(1)
    
    daily_returns_df.replace(np.nan, 0, inplace = True)
    return daily_returns_df

In [100]:
pdr_df = percentage_daily_returns(df)
display(pdr_df)

Ticker       Date      AAPL      BITF      TSLA
0      2020-01-02  0.000000  0.000000  0.000000
1      2020-01-03 -0.009722  0.000000  0.029633
2      2020-01-06  0.007968  0.057592  0.019255
3      2020-01-07 -0.004703  0.269802  0.038801
4      2020-01-08  0.016086 -0.066277  0.049205
...           ...       ...       ...       ...
1514   2026-01-12  0.003393  0.082143  0.008876
1515   2026-01-13  0.003074  0.026403 -0.003920
1516   2026-01-14 -0.004175 -0.054662 -0.017889
1517   2026-01-15 -0.006732 -0.034014 -0.001434
1518   2026-01-16 -0.010379  0.038732 -0.002440

[1519 rows x 4 columns]

In [101]:
df

Ticker       Date        AAPL   BITF        TSLA
0      2020-01-02   72.468254  0.382   28.684000
1      2020-01-03   71.763718  0.382   29.534000
2      2020-01-06   72.335556  0.404   30.102667
3      2020-01-07   71.995361  0.513   31.270666
4      2020-01-08   73.153488  0.479   32.809334
...           ...         ...    ...         ...
1514   2026-01-12  260.250000  3.030  448.959991
1515   2026-01-13  261.049988  3.110  447.200012
1516   2026-01-14  259.959991  2.940  439.200012
1517   2026-01-15  258.209991  2.840  438.570007
1518   2026-01-16  255.529999  2.950  437.500000

[1519 rows x 4 columns]

# Creating a Function to plot graphs

In [112]:
def plot_financial_data(df, title):
    
    fig = px.line(title = title)
    
    for column in df.columns[1:]:

        fig.add_scatter(
            x = df["Date"],
            y = df[column],
            name = column
        )
        fig.update_layout(
            template = 'plotly_dark',
            xaxis_title = "Date"
        )
    fig.show()

In [113]:
plot_financial_data(df, "Adjusted Closing Price of Stocks [$]")